/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

/**
 *
 * @author Usuario
 */
public class appWindow extends javax.swing.JFrame {

    /**
     * Creates new form appWindow
     */
    public appWindow() {
        initComponents();

        this.setLocationRelativeTo(null); // Centrar la ventana en la pantalla

        // Poner como primera vista la página principal
        this.jPnlHome.setVisible(true);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPnlMostrarMaterias = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPnlMostrarAlumnos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPnlAltaDeAlumnos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPnlAsignarCalificaciones = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPnlPromedioTotal = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPnlPromedioParcial = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPnlAlumnosReprobadas = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPnlExtraordinarios = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPnlHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAlumnos = new javax.swing.JMenuItem();
        jMenuMaterias = new javax.swing.JMenuItem();
        jMenuAltaAlumnos = new javax.swing.JMenu();
        jMenuAsignarCalificaciones = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuItemPromedioTotal = new javax.swing.JMenuItem();
        jMenuItemPromedioParcial = new javax.swing.JMenuItem();
        jMenuItemAlumnosReprobadas = new javax.swing.JMenuItem();
        jMenuItemExtraordinarios = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema de control escolar");
        setResizable(false);

        jPnlMostrarMaterias.setBackground(new java.awt.Color(153, 255, 102));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setText("Mostrar Materias");

        javax.swing.GroupLayout jPnlMostrarMateriasLayout = new javax.swing.GroupLayout(jPnlMostrarMaterias);
        jPnlMostrarMaterias.setLayout(jPnlMostrarMateriasLayout);
        jPnlMostrarMateriasLayout.setHorizontalGroup(
            jPnlMostrarMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMostrarMateriasLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel2)
                .addContainerGap(200, Short.MAX_VALUE))
        );
        jPnlMostrarMateriasLayout.setVerticalGroup(
            jPnlMostrarMateriasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMostrarMateriasLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel2)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPnlMostrarAlumnos.setBackground(new java.awt.Color(255, 51, 102));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel3.setText("Mostrar Alumnos");

        javax.swing.GroupLayout jPnlMostrarAlumnosLayout = new javax.swing.GroupLayout(jPnlMostrarAlumnos);
        jPnlMostrarAlumnos.setLayout(jPnlMostrarAlumnosLayout);
        jPnlMostrarAlumnosLayout.setHorizontalGroup(
            jPnlMostrarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMostrarAlumnosLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel3)
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPnlMostrarAlumnosLayout.setVerticalGroup(
            jPnlMostrarAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlMostrarAlumnosLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel3)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPnlAltaDeAlumnos.setBackground(new java.awt.Color(255, 51, 102));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel4.setText("Alta de Alumnos");

        javax.swing.GroupLayout jPnlAltaDeAlumnosLayout = new javax.swing.GroupLayout(jPnlAltaDeAlumnos);
        jPnlAltaDeAlumnos.setLayout(jPnlAltaDeAlumnosLayout);
        jPnlAltaDeAlumnosLayout.setHorizontalGroup(
            jPnlAltaDeAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAltaDeAlumnosLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel4)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPnlAltaDeAlumnosLayout.setVerticalGroup(
            jPnlAltaDeAlumnosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAltaDeAlumnosLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel4)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPnlAsignarCalificaciones.setBackground(new java.awt.Color(255, 51, 102));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Asignar calificaciones");

        javax.swing.GroupLayout jPnlAsignarCalificacionesLayout = new javax.swing.GroupLayout(jPnlAsignarCalificaciones);
        jPnlAsignarCalificaciones.setLayout(jPnlAsignarCalificacionesLayout);
        jPnlAsignarCalificacionesLayout.setHorizontalGroup(
            jPnlAsignarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAsignarCalificacionesLayout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addComponent(jLabel5)
                .addContainerGap(177, Short.MAX_VALUE))
        );
        jPnlAsignarCalificacionesLayout.setVerticalGroup(
            jPnlAsignarCalificacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAsignarCalificacionesLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel5)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPnlPromedioTotal.setBackground(new java.awt.Color(255, 51, 102));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Promedio total");

        javax.swing.GroupLayout jPnlPromedioTotalLayout = new javax.swing.GroupLayout(jPnlPromedioTotal);
        jPnlPromedioTotal.setLayout(jPnlPromedioTotalLayout);
        jPnlPromedioTotalLayout.setHorizontalGroup(
            jPnlPromedioTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPromedioTotalLayout.createSequentialGroup()
                .addGap(221, 221, 221)
                .addComponent(jLabel6)
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPnlPromedioTotalLayout.setVerticalGroup(
            jPnlPromedioTotalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPromedioTotalLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel6)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPnlPromedioParcial.setBackground(new java.awt.Color(255, 51, 102));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Promedio parcial");

        javax.swing.GroupLayout jPnlPromedioParcialLayout = new javax.swing.GroupLayout(jPnlPromedioParcial);
        jPnlPromedioParcial.setLayout(jPnlPromedioParcialLayout);
        jPnlPromedioParcialLayout.setHorizontalGroup(
            jPnlPromedioParcialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPromedioParcialLayout.createSequentialGroup()
                .addGap(207, 207, 207)
                .addComponent(jLabel7)
                .addContainerGap(207, Short.MAX_VALUE))
        );
        jPnlPromedioParcialLayout.setVerticalGroup(
            jPnlPromedioParcialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlPromedioParcialLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel7)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPnlAlumnosReprobadas.setBackground(new java.awt.Color(255, 51, 102));
        jPnlAlumnosReprobadas.setPreferredSize(new java.awt.Dimension(640, 360));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Alumnos Reprobadas");

        javax.swing.GroupLayout jPnlAlumnosReprobadasLayout = new javax.swing.GroupLayout(jPnlAlumnosReprobadas);
        jPnlAlumnosReprobadas.setLayout(jPnlAlumnosReprobadasLayout);
        jPnlAlumnosReprobadasLayout.setHorizontalGroup(
            jPnlAlumnosReprobadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAlumnosReprobadasLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(jLabel8)
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPnlAlumnosReprobadasLayout.setVerticalGroup(
            jPnlAlumnosReprobadasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlAlumnosReprobadasLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel8)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jPnlExtraordinarios.setBackground(new java.awt.Color(255, 51, 102));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Extraordinarios");

        javax.swing.GroupLayout jPnlExtraordinariosLayout = new javax.swing.GroupLayout(jPnlExtraordinarios);
        jPnlExtraordinarios.setLayout(jPnlExtraordinariosLayout);
        jPnlExtraordinariosLayout.setHorizontalGroup(
            jPnlExtraordinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlExtraordinariosLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(jLabel9)
                .addContainerGap(218, Short.MAX_VALUE))
        );
        jPnlExtraordinariosLayout.setVerticalGroup(
            jPnlExtraordinariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlExtraordinariosLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel9)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel1.setText("Página principal");

        javax.swing.GroupLayout jPnlHomeLayout = new javax.swing.GroupLayout(jPnlHome);
        jPnlHome.setLayout(jPnlHomeLayout);
        jPnlHomeLayout.setHorizontalGroup(
            jPnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHomeLayout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(jLabel1)
                .addContainerGap(213, Short.MAX_VALUE))
        );
        jPnlHomeLayout.setVerticalGroup(
            jPnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlHomeLayout.createSequentialGroup()
                .addGap(162, 162, 162)
                .addComponent(jLabel1)
                .addContainerGap(162, Short.MAX_VALUE))
        );

        jMenu3.setText("Mostrar");

        jMenuItemAlumnos.setText("Alumnos");
        jMenuItemAlumnos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlumnosActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItemAlumnos);

        jMenuMaterias.setText("Materias");
        jMenuMaterias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuMateriasActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuMaterias);

        jMenuBar1.add(jMenu3);

        jMenuAltaAlumnos.setText("Alta de alumnos");
        jMenuAltaAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAltaAlumnosMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAltaAlumnos);

        jMenuAsignarCalificaciones.setText("Asignar calificaciones");
        jMenuAsignarCalificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuAsignarCalificacionesMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuAsignarCalificaciones);

        jMenu6.setText("Reportes");

        jMenuItemPromedioTotal.setText("Promedio total de alumnos");
        jMenuItemPromedioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPromedioTotalActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPromedioTotal);

        jMenuItemPromedioParcial.setText("Promedio parcial de alumnos");
        jMenuItemPromedioParcial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemPromedioParcialActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemPromedioParcial);

        jMenuItemAlumnosReprobadas.setText("Alumnos con materias reprobadas");
        jMenuItemAlumnosReprobadas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemAlumnosReprobadasActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemAlumnosReprobadas);

        jMenuItemExtraordinarios.setText("Extraordinarios");
        jMenuItemExtraordinarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExtraordinariosActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItemExtraordinarios);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMostrarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlMostrarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlAltaDeAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlAsignarCalificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlPromedioTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlPromedioParcial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlAlumnosReprobadas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlExtraordinarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlMostrarAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlMostrarMaterias, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlAltaDeAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlAsignarCalificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlPromedioTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlPromedioParcial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlAlumnosReprobadas, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlExtraordinarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPnlHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemAlumnosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemAlumnosActionPerformed
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(true);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(false);
    }//GEN-LAST:event_jMenuItemAlumnosActionPerformed

    private void jMenuAltaAlumnosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAltaAlumnosMouseClicked
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(true);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(false);
    }//GEN-LAST:event_jMenuAltaAlumnosMouseClicked

    private void jMenuAsignarCalificacionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuAsignarCalificacionesMouseClicked
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(true);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(false);
    }//GEN-LAST:event_jMenuAsignarCalificacionesMouseClicked

    private void jMenuMateriasActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(true);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(false);
    }                                                                                                     

    private void jMenuItemPromedioTotalActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(true);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(false);
    }                                                      

    private void jMenuItemPromedioParcialActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(true);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(false);
    }                                                        

    private void jMenuItemAlumnosReprobadasActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(true);
        this.jPnlExtraordinarios.setVisible(false);
    }                                                          

    private void jMenuItemExtraordinariosActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        this.jPnlHome.setVisible(false);
        this.jPnlMostrarAlumnos.setVisible(false);
        this.jPnlMostrarMaterias.setVisible(false);
        this.jPnlAltaDeAlumnos.setVisible(false);
        this.jPnlAsignarCalificaciones.setVisible(false);
        this.jPnlPromedioTotal.setVisible(false);
        this.jPnlPromedioParcial.setVisible(false);
        this.jPnlAlumnosReprobadas.setVisible(false);
        this.jPnlExtraordinarios.setVisible(true);
    }                                                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(appWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(appWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(appWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(appWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new appWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenuAltaAlumnos;
    private javax.swing.JMenu jMenuAsignarCalificaciones;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItemAlumnos;
    private javax.swing.JMenuItem jMenuItemAlumnosReprobadas;
    private javax.swing.JMenuItem jMenuItemExtraordinarios;
    private javax.swing.JMenuItem jMenuItemPromedioParcial;
    private javax.swing.JMenuItem jMenuItemPromedioTotal;
    private javax.swing.JMenuItem jMenuMaterias;
    private javax.swing.JPanel jPnlAltaDeAlumnos;
    private javax.swing.JPanel jPnlAlumnosReprobadas;
    private javax.swing.JPanel jPnlAsignarCalificaciones;
    private javax.swing.JPanel jPnlExtraordinarios;
    private javax.swing.JPanel jPnlHome;
    private javax.swing.JPanel jPnlMostrarAlumnos;
    private javax.swing.JPanel jPnlMostrarMaterias;
    private javax.swing.JPanel jPnlPromedioParcial;
    private javax.swing.JPanel jPnlPromedioTotal;
    // End of variables declaration//GEN-END:variables
}
